name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please attach screenshots if applicable.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      validations:
        required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the extension are you running?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Optional.
